blank_issues_enabled: false
contact_links:
  - name: Fluidd
    url: https://github.com/fluidd-core/fluidd
    about: The Fluidd GitHub repository
  - name: Fluidd Discord Server
    url: https://discord.gg/fluidd
    about: Fluidd related questions and general support
  - name: Twitter contact
    url: https://twitter.com/pedrolamas
    about: Quickest way to get in contact
